name: carrom_scorekeeper
description: "A professional carrom scoring app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audioplayers: ^6.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  # Diese Kombination ist stabil und löst den Konflikt:
  firebase_core: ^3.10.1
  firebase_database: ^11.1.7
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  # Hier sind die Assets nun korrekt eingerückt ergänzt:
  assets:
    - assets/click.mp3
    - assets/icon/app_icon.png