// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQJ74JjH7ScrJ4b5Frl6bRbxcfX-uR4o',
    appId: '1:577715327752:web:e442aad6852d3cb42252bd',
    messagingSenderId: '577715327752',
    projectId: 'carrom-scorekeeper',
    authDomain: 'carrom-scorekeeper.firebaseapp.com',
    databaseURL: 'https://carrom-scorekeeper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carrom-scorekeeper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgpOPt0aRfsW_P6UB91Tktj4MbFH5q3M',
    appId: '1:577715327752:android:b61531b092b45c0f2252bd',
    messagingSenderId: '577715327752',
    projectId: 'carrom-scorekeeper',
    databaseURL: 'https://carrom-scorekeeper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carrom-scorekeeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuac9pc7ped-rauLEvSJofh_Af0cVwqE',
    appId: '1:577715327752:ios:58340f399311f1752252bd',
    messagingSenderId: '577715327752',
    projectId: 'carrom-scorekeeper',
    databaseURL: 'https://carrom-scorekeeper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carrom-scorekeeper.firebasestorage.app',
    iosBundleId: 'com.example.carromScorekeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuuac9pc7ped-rauLEvSJofh_Af0cVwqE',
    appId: '1:577715327752:ios:58340f399311f1752252bd',
    messagingSenderId: '577715327752',
    projectId: 'carrom-scorekeeper',
    databaseURL: 'https://carrom-scorekeeper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carrom-scorekeeper.firebasestorage.app',
    iosBundleId: 'com.example.carromScorekeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQJ74JjH7ScrJ4b5Frl6bRbxcfX-uR4o',
    appId: '1:577715327752:web:310d05eeca5451e82252bd',
    messagingSenderId: '577715327752',
    projectId: 'carrom-scorekeeper',
    authDomain: 'carrom-scorekeeper.firebaseapp.com',
    databaseURL: 'https://carrom-scorekeeper-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carrom-scorekeeper.firebasestorage.app',
  );
}
